spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 20
      minimum-idle: 10
  profiles:
    active: anotation
server:
  port: 8877
mybatis:
  config-location: classpath:mybatismybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    cache-enabled: true